import = [
 "~/.config/alacritty/theme/rose-pine.toml"
]

[env]
TERM="xterm-256color"

[cursor]
blink_interval = 0
style = "Block"

[font]
size = 12.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"


[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"


[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
opacity = 1
dynamic_title = false

[window.padding]
x = 10
y = 10
